"""数据模型包"""
from models.schema import (
    CATEGORY_MAP, MAJOR_CATEGORIES, LOCATION_SYNONYMS,
    JOB_TYPE_MAP, INDUSTRY_KEYWORDS, WELFARE_KEYWORDS,
    QUICK_SCENARIOS, BRAND_COLORS, BRAND_ICON, TOP_COMPANIES,
    BENEFIT_MAP, get_major_cat
)
